create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  full_name text,
  avatar_url text,
  role text not null default 'buyer' check (role in ('buyer', 'seller', 'admin')),
  status text not null default 'active' check (status in ('active', 'suspended', 'banned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  balance numeric(12, 2) not null default 0,
  currency text not null default 'GHS',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  wallet_id bigint not null references public.wallets(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('deposit', 'purchase_hold', 'release', 'refund', 'withdrawal')),
  payment_method text,
  amount numeric(12, 2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'completed', 'failed', 'cancelled')),
  reference text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_table text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  seller_id uuid references public.profiles(id) on delete set null,
  game text not null,
  title text not null,
  description text,
  price numeric(12, 2) not null default 0,
  platform text not null default 'PC',
  region text not null default 'Global',
  account_level integer not null default 1,
  rank text not null default 'Unranked',
  inventory_details text,
  transfer_method text,
  ban_history text,
  status text not null default 'pending_review',
  views integer not null default 0,
  seller_name text not null default 'Demo Seller',
  seller_rating numeric(3, 2) not null default 0,
  seller_sales integer not null default 0,
  seller_verified boolean not null default false,
  cover_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'active'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (
    new.id,
    new.email,
    case
      when lower(new.email) = 'adnansalman169@gmail.com' then 'admin'
      else 'buyer'
    end
  )
  on conflict (id) do update
  set email = excluded.email,
      role = case
        when lower(excluded.email) = 'adnansalman169@gmail.com' then 'admin'
        else public.profiles.role
      end,
      updated_at = now();

  insert into public.wallets (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.listings enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users can read own wallet" on public.wallets;
create policy "Users can read own wallet"
on public.wallets
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can read own wallet transactions" on public.wallet_transactions;
create policy "Users can read own wallet transactions"
on public.wallet_transactions
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Admins can read audit logs" on public.admin_audit_logs;
create policy "Admins can read audit logs"
on public.admin_audit_logs
for select
using (public.is_admin());

drop policy if exists "Anyone can read active listings" on public.listings;
create policy "Anyone can read active listings"
on public.listings
for select
using (status = 'active');

drop policy if exists "Anyone can submit pending listings" on public.listings;
create policy "Anyone can submit pending listings"
on public.listings
for insert
with check (auth.uid() is not null and status = 'pending_review');

-- Prototype admin control policies.
-- For production, replace these with authenticated admin-only RLS checks.
drop policy if exists "Prototype admin can read all listings" on public.listings;
drop policy if exists "Admins can read all listings" on public.listings;
create policy "Admins can read all listings"
on public.listings
for select
using (public.is_admin());

drop policy if exists "Prototype admin can delete listings" on public.listings;
drop policy if exists "Admins can delete listings" on public.listings;
create policy "Admins can delete listings"
on public.listings
for delete
using (public.is_admin());

delete from public.listings
where seller_name in ('KofiRanked', 'NanaCarry', 'AmaPlayz', 'TurboYaw', 'QuestVault', 'RankLift');
