create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  full_name text,
  avatar_url text,
  role text not null default 'buyer' check (role in ('buyer', 'seller', 'admin')),
  status text not null default 'active' check (status in ('active', 'suspended', 'banned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  balance numeric(12, 2) not null default 0,
  currency text not null default 'GHS',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  wallet_id bigint not null references public.wallets(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('deposit', 'purchase_hold', 'release', 'refund', 'withdrawal')),
  payment_method text,
  amount numeric(12, 2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'completed', 'failed', 'cancelled')),
  reference text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_table text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.escrow_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_reference text not null default 'GTH-2409',
  action text not null check (action in ('confirm_received', 'pause_release', 'open_dispute')),
  status text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_reference text not null default 'GTH-2409',
  reason text not null,
  description text not null,
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'rejected')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.app_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  activity_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  seller_id uuid references public.profiles(id) on delete set null,
  game text not null,
  title text not null,
  description text,
  price numeric(12, 2) not null default 0,
  platform text not null default 'PC',
  region text not null default 'Global',
  account_level integer not null default 1,
  rank text not null default 'Unranked',
  inventory_details text,
  transfer_method text,
  ban_history text,
  status text not null default 'pending_review',
  views integer not null default 0,
  seller_name text not null default 'Demo Seller',
  seller_rating numeric(3, 2) not null default 0,
  seller_sales integer not null default 0,
  seller_verified boolean not null default false,
  successful_deliveries integer not null default 0,
  dispute_count integer not null default 0,
  refund_count integer not null default 0,
  cover_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.listings add column if not exists successful_deliveries integer not null default 0;
alter table public.listings add column if not exists dispute_count integer not null default 0;
alter table public.listings add column if not exists refund_count integer not null default 0;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'active'
  );
$$;

create or replace function public.handle_verified_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email_confirmed_at is null then
    return new;
  end if;

  insert into public.profiles (id, email, role)
  values (
    new.id,
    new.email,
    case
      when lower(new.email) = 'adnansalman169@gmail.com' then 'admin'
      else 'buyer'
    end
  )
  on conflict (id) do update
  set email = excluded.email,
      role = case
        when lower(excluded.email) = 'adnansalman169@gmail.com' then 'admin'
        else public.profiles.role
      end,
      updated_at = now();

  insert into public.wallets (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
drop trigger if exists on_auth_user_verified on auth.users;
create trigger on_auth_user_verified
after insert or update of email_confirmed_at on auth.users
for each row
when (new.email_confirmed_at is not null)
execute procedure public.handle_verified_user();

alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.escrow_events enable row level security;
alter table public.disputes enable row level security;
alter table public.app_activities enable row level security;
alter table public.listings enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users can read own wallet" on public.wallets;
create policy "Users can read own wallet"
on public.wallets
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can insert own wallet" on public.wallets;
create policy "Users can insert own wallet"
on public.wallets
for insert
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can read own wallet transactions" on public.wallet_transactions;
create policy "Users can read own wallet transactions"
on public.wallet_transactions
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can insert own wallet transactions" on public.wallet_transactions;
create policy "Users can insert own wallet transactions"
on public.wallet_transactions
for insert
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Admins can read audit logs" on public.admin_audit_logs;
create policy "Admins can read audit logs"
on public.admin_audit_logs
for select
using (public.is_admin());

drop policy if exists "Users can read own escrow events" on public.escrow_events;
create policy "Users can read own escrow events"
on public.escrow_events
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can insert own escrow events" on public.escrow_events;
create policy "Users can insert own escrow events"
on public.escrow_events
for insert
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can read own disputes" on public.disputes;
create policy "Users can read own disputes"
on public.disputes
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can insert own disputes" on public.disputes;
create policy "Users can insert own disputes"
on public.disputes
for insert
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can read own app activities" on public.app_activities;
create policy "Users can read own app activities"
on public.app_activities
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can insert own app activities" on public.app_activities;
create policy "Users can insert own app activities"
on public.app_activities
for insert
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can read own sellers row" on public.sellers;
create policy "Users can read own sellers row"
on public.sellers
for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "Sellers can manage own products" on public.products;
create policy "Sellers can manage own products"
on public.products
for all
using (auth.uid() = seller_id or public.is_admin())
with check (auth.uid() = seller_id or public.is_admin());

drop policy if exists "Users can read related orders" on public.orders;
create policy "Users can read related orders"
on public.orders
for select
using (auth.uid() = buyer_id or auth.uid() = seller_id or public.is_admin());

drop policy if exists "Users can read related payments" on public.payments;
create policy "Users can read related payments"
on public.payments
for select
using (auth.uid() = buyer_id or public.is_admin());

drop policy if exists "Users can insert related seller proofs" on public.seller_proofs;
create policy "Users can insert related seller proofs"
on public.seller_proofs
for insert
with check (auth.uid() = seller_id or public.is_admin());

drop policy if exists "Users can read related seller proofs" on public.seller_proofs;
create policy "Users can read related seller proofs"
on public.seller_proofs
for select
using (auth.uid() = seller_id or public.is_admin());

drop policy if exists "Users can insert related shipments" on public.shipments;
create policy "Users can insert related shipments"
on public.shipments
for insert
with check (auth.uid() = seller_id or public.is_admin());

drop policy if exists "Users can read related shipments" on public.shipments;
create policy "Users can read related shipments"
on public.shipments
for select
using (auth.uid() = seller_id or public.is_admin());

drop policy if exists "Sellers can submit secure deliveries" on public.secure_deliveries;
create policy "Sellers can submit secure deliveries"
on public.secure_deliveries
for insert
with check (auth.uid() = seller_id or public.is_admin());

drop policy if exists "Related users can read secure deliveries after payment hold" on public.secure_deliveries;
create policy "Related users can read secure deliveries after payment hold"
on public.secure_deliveries
for select
using (
  public.is_admin()
  or auth.uid() = seller_id
  or exists (
    select 1
    from public.orders
    where orders.id = secure_deliveries.order_id
      and orders.buyer_id = auth.uid()
      and orders.status in (
        'PAYMENT_HELD',
        'SELLER_PROOF_SUBMITTED',
        'PROOF_APPROVED',
        'READY_TO_SHIP',
        'SHIPPED',
        'DELIVERED',
        'BUYER_CONFIRMED',
        'COMPLETED',
        'SELLER_PAID'
      )
  )
);

drop policy if exists "Users can read related payouts" on public.payouts;
create policy "Users can read related payouts"
on public.payouts
for select
using (auth.uid() = seller_id or public.is_admin());

drop policy if exists "Users can read own notifications" on public.notifications;
create policy "Users can read own notifications"
on public.notifications
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Anyone can read seller trust scores" on public.seller_trust_scores;
create policy "Anyone can read seller trust scores"
on public.seller_trust_scores
for select
using (true);

drop policy if exists "Users can read own buyer trust score" on public.buyer_trust_scores;
create policy "Users can read own buyer trust score"
on public.buyer_trust_scores
for select
using (auth.uid() = buyer_id or public.is_admin());

drop policy if exists "Anyone can read active listings" on public.listings;
create policy "Anyone can read active listings"
on public.listings
for select
using (status = 'active');

drop policy if exists "Anyone can submit pending listings" on public.listings;
create policy "Anyone can submit pending listings"
on public.listings
for insert
with check (auth.uid() is not null and status = 'pending_review');

-- Prototype admin control policies.
-- For production, replace these with authenticated admin-only RLS checks.
drop policy if exists "Prototype admin can read all listings" on public.listings;
drop policy if exists "Admins can read all listings" on public.listings;
create policy "Admins can read all listings"
on public.listings
for select
using (public.is_admin());

drop policy if exists "Prototype admin can delete listings" on public.listings;
drop policy if exists "Admins can delete listings" on public.listings;
create policy "Admins can delete listings"
on public.listings
for delete
using (public.is_admin());

delete from public.listings
where seller_name in ('KofiRanked', 'NanaCarry', 'AmaPlayz', 'TurboYaw', 'QuestVault', 'RankLift');

-- Marketplace wallet payment system.
-- Run this full file in Supabase SQL Editor after changing wallet/order behavior.

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  role text not null default 'buyer' check (role in ('buyer', 'seller', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.wallets add column if not exists held_balance numeric(12, 2) not null default 0;
alter table public.wallets add column if not exists available_balance numeric(12, 2) generated always as (balance) stored;

do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.wallet_transactions'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%transaction_type%'
  loop
    execute format('alter table public.wallet_transactions drop constraint %I', constraint_record.conname);
  end loop;

  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.wallet_transactions'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%status%'
  loop
    execute format('alter table public.wallet_transactions drop constraint %I', constraint_record.conname);
  end loop;
end $$;

alter table public.wallet_transactions
  add constraint wallet_transactions_type_check
  check (transaction_type in (
    'DEPOSIT',
    'PURCHASE_HOLD',
    'REFUND',
    'SELLER_RELEASE',
    'COMMISSION',
    'WITHDRAWAL_REQUEST',
    'WITHDRAWAL_PAID',
    'WITHDRAWAL_REJECTED'
  ));

alter table public.wallet_transactions
  add constraint wallet_transactions_status_check
  check (status in (
    'PENDING',
    'DEPOSIT_SUCCESSFUL',
    'PAYMENT_HELD',
    'REFUNDED',
    'COMPLETED',
    'SELLER_PAID',
    'WITHDRAWAL_REQUESTED',
    'WITHDRAWAL_PAID',
    'WITHDRAWAL_REJECTED',
    'FAILED',
    'CANCELLED'
  ));

alter table public.wallet_transactions
  alter column status set default 'PENDING';

do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.orders'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%status%'
  loop
    execute format('alter table public.orders drop constraint %I', constraint_record.conname);
  end loop;
end $$;

alter table public.orders
  add constraint orders_status_check
  check (status in (
    'PENDING_PAYMENT',
    'PAYMENT_HELD',
    'SELLER_PROOF_REQUIRED',
    'SELLER_PROOF_SUBMITTED',
    'PROOF_APPROVED',
    'PROOF_REJECTED',
    'READY_TO_SHIP',
    'SHIPPED',
    'DELIVERED',
    'BUYER_CONFIRMED',
    'DISPUTED',
    'REFUNDED',
    'COMPLETED',
    'SELLER_PAID'
  ));

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  price numeric(12, 2) not null check (price >= 0),
  game text,
  status text not null default 'ACTIVE' check (status in ('DRAFT', 'ACTIVE', 'SOLD', 'SUSPENDED', 'DELETED')),
  cover_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sellers (
  id uuid primary key references public.profiles(id) on delete cascade,
  business_name text,
  verification_status text not null default 'PENDING' check (verification_status in ('PENDING', 'VERIFIED', 'SUSPENDED', 'REJECTED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  seller_id uuid references public.profiles(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  listing_id bigint references public.listings(id) on delete set null,
  amount numeric(12, 2) not null check (amount >= 0),
  held_amount numeric(12, 2) not null default 0,
  commission_amount numeric(12, 2) not null default 0,
  inspection_period_hours integer not null default 24 check (inspection_period_hours in (24, 48, 72)),
  inspection_started_at timestamptz,
  auto_release_at timestamptz,
  status text not null default 'PENDING_PAYMENT' check (
    status in (
      'PENDING_PAYMENT',
      'PAYMENT_HELD',
      'SELLER_PROOF_REQUIRED',
      'SELLER_PROOF_SUBMITTED',
      'PROOF_APPROVED',
      'PROOF_REJECTED',
      'DELIVERED',
      'BUYER_CONFIRMED',
      'DISPUTED',
      'REFUNDED',
      'COMPLETED',
      'SELLER_PAID'
    )
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists inspection_period_hours integer not null default 24;
alter table public.orders add column if not exists inspection_started_at timestamptz;
alter table public.orders add column if not exists auto_release_at timestamptz;

create table if not exists public.order_payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12, 2) not null,
  status text not null default 'PAYMENT_HELD',
  provider text not null default 'WALLET',
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null,
  provider_reference text,
  amount numeric(12, 2) not null check (amount >= 0),
  status text not null default 'PAYMENT_HELD' check (status in ('PENDING_PAYMENT', 'PAYMENT_HELD', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', 'RELEASED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_proofs (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  proof_type text not null default 'VIDEO',
  proof_url text,
  notes text,
  status text not null default 'SELLER_PROOF_SUBMITTED' check (status in ('SELLER_PROOF_SUBMITTED', 'PROOF_APPROVED', 'PROOF_REJECTED')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  delivery_notes text not null,
  status text not null default 'DELIVERED' check (status in ('DELIVERED', 'BUYER_CONFIRMED', 'DISPUTED')),
  created_at timestamptz not null default now()
);

create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  carrier text,
  tracking_number text not null,
  tracking_url text,
  status text not null default 'SHIPPED' check (status in ('READY_TO_SHIP', 'SHIPPED', 'DELIVERED', 'DISPUTED')),
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create table if not exists public.secure_deliveries (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  login_identifier text not null,
  password_secret text not null,
  backup_codes text,
  transfer_instructions text not null,
  platform_details text not null,
  original_email_access_status text not null,
  status text not null default 'SUBMITTED' check (status in ('SUBMITTED', 'VIEWED_BY_BUYER', 'REPLACED', 'LOCKED')),
  created_at timestamptz not null default now(),
  viewed_at timestamptz
);

create table if not exists public.dispute_messages (
  id bigint generated by default as identity primary key,
  dispute_id bigint not null references public.disputes(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.seller_balances (
  id bigint generated by default as identity primary key,
  seller_id uuid not null unique references public.profiles(id) on delete cascade,
  available_balance numeric(12, 2) not null default 0,
  pending_balance numeric(12, 2) not null default 0,
  currency text not null default 'GHS',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  payment_method text not null,
  status text not null default 'PENDING' check (status in ('PENDING', 'APPROVED', 'PAID', 'REJECTED')),
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.platform_commissions (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete set null,
  amount numeric(12, 2) not null default 0,
  rate numeric(5, 2) not null default 10,
  created_at timestamptz not null default now()
);

create table if not exists public.payouts (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete set null,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12, 2) not null check (amount >= 0),
  provider text,
  status text not null default 'PENDING' check (status in ('PENDING', 'APPROVED', 'PAID', 'REJECTED')),
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  status text not null default 'UNREAD' check (status in ('UNREAD', 'READ')),
  created_at timestamptz not null default now()
);

create table if not exists public.seller_trust_scores (
  seller_id uuid primary key references public.profiles(id) on delete cascade,
  total_sales integer not null default 0,
  successful_deliveries integer not null default 0,
  dispute_count integer not null default 0,
  refund_count integer not null default 0,
  average_rating numeric(3, 2) not null default 0,
  verified_badge boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.buyer_trust_scores (
  buyer_id uuid primary key references public.profiles(id) on delete cascade,
  completed_purchases integer not null default 0,
  dispute_count integer not null default 0,
  account_created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.sellers enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_payments enable row level security;
alter table public.payments enable row level security;
alter table public.seller_proofs enable row level security;
alter table public.deliveries enable row level security;
alter table public.shipments enable row level security;
alter table public.secure_deliveries enable row level security;
alter table public.disputes enable row level security;
alter table public.dispute_messages enable row level security;
alter table public.seller_balances enable row level security;
alter table public.withdrawals enable row level security;
alter table public.payouts enable row level security;
alter table public.platform_commissions enable row level security;
alter table public.notifications enable row level security;
alter table public.seller_trust_scores enable row level security;
alter table public.buyer_trust_scores enable row level security;

create or replace function public.process_deposit_success(
  p_user_id uuid,
  p_amount numeric,
  p_provider text,
  p_reference text
)
returns public.wallet_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet_id bigint;
  v_transaction public.wallet_transactions;
begin
  if auth.uid() <> p_user_id and not public.is_admin() then
    raise exception 'Not allowed';
  end if;
  if p_amount <= 0 then
    raise exception 'Deposit amount must be positive';
  end if;

  insert into public.wallets (user_id, balance)
  values (p_user_id, 0)
  on conflict (user_id) do nothing;

  select id into v_wallet_id from public.wallets where user_id = p_user_id for update;

  update public.wallets
  set balance = balance + p_amount,
      updated_at = now()
  where id = v_wallet_id;

  insert into public.wallet_transactions (
    wallet_id,
    user_id,
    transaction_type,
    payment_method,
    amount,
    status,
    reference
  )
  values (
    v_wallet_id,
    p_user_id,
    'DEPOSIT',
    p_provider,
    p_amount,
    'DEPOSIT_SUCCESSFUL',
    p_reference
  )
  returning * into v_transaction;

  return v_transaction;
end;
$$;

create or replace function public.buy_with_wallet(
  p_buyer_id uuid,
  p_listing_id bigint,
  p_amount numeric
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet public.wallets;
  v_order public.orders;
  v_seller_id uuid;
begin
  if auth.uid() <> p_buyer_id and not public.is_admin() then
    raise exception 'Not allowed';
  end if;
  if p_amount <= 0 then
    raise exception 'Purchase amount must be positive';
  end if;

  select * into v_wallet from public.wallets where user_id = p_buyer_id for update;
  if v_wallet.id is null or v_wallet.balance < p_amount then
    raise exception 'Insufficient wallet balance';
  end if;

  select seller_id into v_seller_id from public.listings where id = p_listing_id;

  update public.wallets
  set balance = balance - p_amount,
      held_balance = held_balance + p_amount,
      updated_at = now()
  where id = v_wallet.id;

  insert into public.orders (buyer_id, seller_id, listing_id, amount, held_amount, status)
  values (p_buyer_id, v_seller_id, p_listing_id, p_amount, p_amount, 'PAYMENT_HELD')
  returning * into v_order;

  insert into public.order_payments (order_id, buyer_id, amount, status, provider)
  values (v_order.id, p_buyer_id, p_amount, 'PAYMENT_HELD', 'WALLET');

  insert into public.wallet_transactions (wallet_id, user_id, transaction_type, amount, status, reference)
  values (v_wallet.id, p_buyer_id, 'PURCHASE_HOLD', p_amount, 'PAYMENT_HELD', 'ORDER-' || v_order.id);

  return v_order;
end;
$$;

create or replace function public.create_trade_assurance_order(
  p_buyer_id uuid,
  p_listing_id bigint,
  p_amount numeric,
  p_provider text default 'Visa card'
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_seller_id uuid;
begin
  if auth.uid() <> p_buyer_id and not public.is_admin() then
    raise exception 'Not allowed';
  end if;
  if p_amount <= 0 then
    raise exception 'Order amount must be positive';
  end if;

  select seller_id into v_seller_id from public.listings where id = p_listing_id;

  insert into public.orders (buyer_id, seller_id, listing_id, amount, held_amount, status)
  values (p_buyer_id, v_seller_id, p_listing_id, p_amount, p_amount, 'PAYMENT_HELD')
  returning * into v_order;

  insert into public.payments (order_id, buyer_id, provider, provider_reference, amount, status)
  values (v_order.id, p_buyer_id, p_provider, 'TA-' || v_order.id, p_amount, 'PAYMENT_HELD');

  insert into public.order_payments (order_id, buyer_id, amount, status, provider)
  values (v_order.id, p_buyer_id, p_amount, 'PAYMENT_HELD', p_provider);

  insert into public.notifications (user_id, title, body)
  values (
    p_buyer_id,
    'Payment held',
    'Your payment is held under Trade Assurance until delivery is confirmed or a dispute decision is made.'
  );

  return v_order;
end;
$$;

create or replace function public.release_order_to_seller(
  p_order_id bigint,
  p_buyer_id uuid,
  p_commission_rate numeric default 10
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_wallet_id bigint;
  v_commission numeric(12, 2);
  v_seller_amount numeric(12, 2);
begin
  if auth.uid() <> p_buyer_id and not public.is_admin() then
    raise exception 'Not allowed';
  end if;

  select * into v_order
  from public.orders
  where id = p_order_id and buyer_id = p_buyer_id
  for update;

  if v_order.id is null then
    raise exception 'Order not found';
  end if;
  if v_order.status in ('DISPUTED', 'REFUNDED', 'COMPLETED', 'SELLER_PAID') then
    raise exception 'Order cannot be released from current status';
  end if;

  select id into v_wallet_id from public.wallets where user_id = p_buyer_id for update;
  v_commission = round(v_order.held_amount * (p_commission_rate / 100), 2);
  v_seller_amount = v_order.held_amount - v_commission;

  update public.wallets
  set held_balance = greatest(held_balance - v_order.held_amount, 0),
      updated_at = now()
  where id = v_wallet_id;

  insert into public.seller_balances (seller_id, available_balance)
  values (v_order.seller_id, v_seller_amount)
  on conflict (seller_id) do update
  set available_balance = public.seller_balances.available_balance + excluded.available_balance,
      updated_at = now();

  insert into public.platform_commissions (order_id, amount, rate)
  values (v_order.id, v_commission, p_commission_rate);

  insert into public.wallet_transactions (wallet_id, user_id, transaction_type, amount, status, reference)
  values
    (v_wallet_id, p_buyer_id, 'COMMISSION', v_commission, 'COMPLETED', 'ORDER-' || v_order.id),
    (v_wallet_id, p_buyer_id, 'SELLER_RELEASE', v_seller_amount, 'SELLER_PAID', 'ORDER-' || v_order.id);

  update public.orders
  set status = 'COMPLETED',
      commission_amount = v_commission,
      updated_at = now()
  where id = v_order.id
  returning * into v_order;

  return v_order;
end;
$$;

create or replace function public.start_buyer_inspection(
  p_order_id bigint,
  p_seller_id uuid,
  p_inspection_hours integer default 24
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
begin
  if p_inspection_hours not in (24, 48, 72) then
    raise exception 'Inspection period must be 24, 48, or 72 hours';
  end if;

  select * into v_order
  from public.orders
  where id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'Order not found';
  end if;
  if auth.uid() <> p_seller_id and not public.is_admin() then
    raise exception 'Not allowed';
  end if;
  if v_order.status = 'DISPUTED' then
    raise exception 'Inspection cannot start while disputed';
  end if;

  update public.orders
  set status = 'DELIVERED',
      inspection_period_hours = p_inspection_hours,
      inspection_started_at = now(),
      auto_release_at = now() + make_interval(hours => p_inspection_hours),
      updated_at = now()
  where id = p_order_id
  returning * into v_order;

  return v_order;
end;
$$;

create or replace function public.auto_release_order_if_due(
  p_order_id bigint
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
begin
  select * into v_order
  from public.orders
  where id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'Order not found';
  end if;
  if v_order.status = 'DISPUTED' then
    raise exception 'Auto-release blocked by dispute';
  end if;
  if v_order.auto_release_at is null or v_order.auto_release_at > now() then
    raise exception 'Inspection period has not expired';
  end if;

  return public.release_order_to_seller(v_order.id, v_order.buyer_id, 10);
end;
$$;

create or replace function public.refund_order_to_buyer(
  p_order_id bigint,
  p_admin_note text default 'Refund approved'
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_wallet_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Only admin can refund held orders';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  select id into v_wallet_id from public.wallets where user_id = v_order.buyer_id for update;

  update public.wallets
  set balance = balance + v_order.held_amount,
      held_balance = greatest(held_balance - v_order.held_amount, 0),
      updated_at = now()
  where id = v_wallet_id;

  insert into public.wallet_transactions (wallet_id, user_id, transaction_type, amount, status, reference)
  values (v_wallet_id, v_order.buyer_id, 'REFUND', v_order.held_amount, 'REFUNDED', p_admin_note);

  update public.orders
  set status = 'REFUNDED',
      held_amount = 0,
      updated_at = now()
  where id = v_order.id
  returning * into v_order;

  return v_order;
end;
$$;

create or replace function public.request_seller_withdrawal(
  p_seller_id uuid,
  p_amount numeric,
  p_payment_method text
)
returns public.withdrawals
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance public.seller_balances;
  v_withdrawal public.withdrawals;
begin
  if auth.uid() <> p_seller_id and not public.is_admin() then
    raise exception 'Not allowed';
  end if;
  if p_amount <= 0 then
    raise exception 'Withdrawal amount must be positive';
  end if;

  select * into v_balance from public.seller_balances where seller_id = p_seller_id for update;
  if v_balance.id is null or v_balance.available_balance < p_amount then
    raise exception 'Insufficient seller balance';
  end if;

  update public.seller_balances
  set available_balance = available_balance - p_amount,
      pending_balance = pending_balance + p_amount,
      updated_at = now()
  where seller_id = p_seller_id;

  insert into public.withdrawals (seller_id, amount, payment_method, status)
  values (p_seller_id, p_amount, p_payment_method, 'PENDING')
  returning * into v_withdrawal;

  return v_withdrawal;
end;
$$;
